#!/usr/bin/env bash
#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Script to bootstrap a linux box
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

if [[ "$OSTYPE" != "linux"* ]]; then
  echo "$0 : Will only run on Linux"
  exit 1
fi

DIR=$(cd $(dirname "$0"); pwd)

###############################################################################
# apt
###############################################################################

if [[ -f $DIR/packages/apt ]]; then
  exec<$DIR/packages/apt
  while read line
  do
    if [[ ! "$line" =~ (^#|^$) ]]; then
      if [[ -f $DIR/packages/apt-preinstall/"$line" ]]; then
        bash $DIR/packages/apt-preinstall/"$line"
      fi
      apt install $line -y
    fi
  done
fi

###############################################################################
# pip3
###############################################################################

if [[ -f $DIR/packages/pip3 ]]; then
  exec<$DIR/packages/pip3
  while read line
  do
    if [[ ! "$line" =~ (^#|^$) ]]; then
      pip3 install $line
    fi
  done
fi

###############################################################################
# snap
###############################################################################

if [[ -f $DIR/packages/snap ]]; then
  exec<$DIR/packages/snap
  while read line
  do
    if [[ ! "$line" =~ (^#|^$) ]]; then
      snap install $line --classic
    fi
  done
fi

