#!/usr/bin/env bash
#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Script to bootstrap a linux box
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

if [[ "$OSTYPE" != "linux"* ]]; then
  echo "$0 : Will only run on Linux"
  exit 1
fi

DIR=$(cd $(dirname "$0"); pwd)

###############################################################################
# apt-get
###############################################################################

if [[ -f $DIR/packages/apt ]]; then
  exec<$DIR/packages/apt
  while read line
  do
    if [[ ! "$line" =~ (^#|^$) ]]; then
      $line
    fi
  done
fi

###############################################################################
# snap
###############################################################################

if [[ -f $DIR/packages/snap ]]; then
  exec<$DIR/packages/snap
  while read line
  do
    if [[ ! "$line" =~ (^#|^$) ]]; then
      $line
    fi
  done
fi

